### ISSUE TITLE
Summary utilization report is missing decks with only "Sub deck" checked

### ISSUE THREAD

**Issue by aleksejrs** [lune-stone/anki-addon-limit-new-by-young#17]
With only "Sub deck" checked:

Verbose report:
```
=== Young Limit ===

100.00% (4 of 4)	/::nonimp-post::generalpreset::…
100.00% (4 of 4)	/::nonimp-post::generalpreset::…
100.00% (4 of 4)	/::nonimp-post::nip-own_presets::imageocc
100.00% (2 of 2)	/::nonimp-post::generalpreset::lang::d
100.00% (1 of 1)	/::nonimp-post::generalpreset::lang::e::…
100.00% (1 of 1)	/::nonimp-post::generalpreset::lang::e::…::…
100.00% (1 of 1)	/::nonimp-post::generalpreset::lang::e::…::…::…


=== Daily Load Limit ===



=== Soon Limit ===

100.00% (4 of 4)	/::nonimp-post::generalpreset::lang::en
100.00% (4 of 4)	/::nonimp-post::generalpreset::…::…
100.00% (2 of 2)	/::!someprio::nonimp-adva::m2a::…::…::…::…
100.00% (1 of 1)	/::nonimp-post::nip-own_presets::nip-m2a::…
100.00% (1 of 1)	/::nonimp-post::nip-own_presets::nip-m2a::…
100.00% (1 of 1)	/::nonimp-post::nip-own_presets::nip-m2a::…
```

Summary report:

```
=== Limit Summary ===

100.00% (4 of 4)	[soon]	/::nonimp-post::generalpreset::lang::en
```

**Comment by aleksejrs** [comment]
"lang::en" is in the summary report, "imageocc" is not.
"imageocc" is over limit in 2/3 cases, "lang::en"  is under limit in 2/3 cases.
"imageocc" has 100.00% in Young Limit, "lang::en" has 100.00% in Soon Limit.

```
=== Young Limit ===
100.00% (4 of 4)	/::nonimp-post::nip-own_presets::imageocc
0.00% (0 of 2)	/::nonimp-post::generalpreset::lang::en

=== Daily Load Limit ===
146.18% (2.81 of 1.92)	/::nonimp-post::nip-own_presets::imageocc
37.05% (0.36 of 0.96)	/::nonimp-post::generalpreset::lang::en

=== Soon Limit ===
300.00% (24 of 8)	/::nonimp-post::nip-own_presets::imageocc
100.00% (4 of 4)	/::nonimp-post::generalpreset::lang::en
```

**Comment by lune-stone** [comment]
I suspect this is working as intended, but that doesn't necessarily mean it is the best way of doing things.

What is happening here is that the summary is being applied (picking the limit with hightest utilization for each deck) before filtering. The reasoning here is that the summary is close to the "net" effect of the deck, as in the limit that currently controls how many new cards you get for the day.

To put this back into the example above, this means that "lang::en" is visible because it's highest utilization is exactly 100% (young) being neither "over" or "under" limit which is filtered out, and "imageocc" is filtered out because it is over (soon).

You could reverse the filtering/summary steps, but consider the effect that can have. If for example "over" is unchecked and the output shows some <100% value for the deck because of it's second largest utilization. Now you can't tell which rows/decks are going to get new cards the next day (unchecking "over" doesn't always remove the row from the report, instead falling back to the next limit). Checking "over" solves this but now you have "noise" rows again. It's lose-lose.

It would be possible to have additional modes/controls to change the order of operations or do an alternative summary strategy, but I haven't given this idea much thought.

Another thought I had was that it might be best to change "over" from ">100%" to be ">=100%". Decks under these two categories behave about the same (no new cards), so I'm not seeing a lot of reason to keep them separated, and it would perhaps make it a bit more intuitive if no decks are displays when both "under" and "over" are unchecked.

**Comment by lune-stone** [comment]
One bug that exists in the current summary-then-filter approach is "no defined limit" which makes it possible to hide a deck that does have a defined limit, but isn't the "highest" in the sort order.

```
=== Young Limit ===
0.00% (0 of 50)	A

=== Daily Load Limit ===
0.00% (0.19 of ∞)	A

=== Soon Limit ===
0.00% (2 of ∞)	A
```

which is summarized as:
```
=== Limit Summary ===
0.00% (2 of ∞)	[soon]	A
```

and becomes filtered out if "No defined limit" is unchecked.

EDIT it should be possible to include a hidden field that indicates if the deck has any limit defined and filter on that rather than the specific limit used by the summary. Other filters don't seem to need changing as they are either properties of the deck directly (Empty, Not started, Sub deck, etc.), or on the summarized utilization value itself (Over, Under).
