### ISSUE TITLE
How to choose the limits?

### ISSUE THREAD

**Issue by user1823** [lune-stone/anki-addon-limit-new-by-young#3]
What logic should I use to choose the young card limit? Am I supposed to set a random number and see how it affects my daily review count? Or is there a better method?

**Comment by lune-stone** [comment]
It's a good question. In my opinion much like the new card limit, the best value to use depends both on the person and the difficulty of the deck, but there are a few things that can get you into the right ballpark before you start tuning it. Keep in mind that this add-on is still fairly new so "your mileage may vary" on this advice. Feel free to report back later how well it works or doesn't.

First consider what the effect would be if you pick too low a limit. Too low and you will start to see days where you are not overwhelmed in terms of number of reviews, having answered everything well, but are still not getting new cards because you are waiting for the young cards to reach maturity. This can happen if 1) the limit is very low 2) the FSRS stats need to be optimized to better handle the deck being easy, meaning the time to reach maturity is longer than it needs to be 3) it's a new deck and you can't really optimize yet so you have the same issue as number 2 but for a different reason. To avoid this use a minimum of `new cards per day limit * days to mature card given only "good" answers`. Or just increase the limit a bit as soon as you get such a day.

For the opposite end, having the limit too high is a lot like having too many new cards per day, where you start to mentally struggle to recognize one card from another in the pool of the young cards. Dips in retention for young cards combined with extend dips to number of learned cards may be a signal here. After a few days you should have a rough average of cards learned per day. You can apply a small multiplier (1-3) to this number on top of the minimum to get a starting maximum.

Personally I tend to aim around 50-200 for small decks (<1000 cards), and around 150-500 for anything bigger. Most of my decks are set to 10-20 new per day. I also don't consider myself a master of memorizing, or even par, at least for the decks I use if that helps you establish your baseline.

Another thing to keep in mind is this add-on can make your decks more sensitive to leeches as they can stick in the young category for longer periods of time than other cards depending on your settings. 

As this isn't well documented at the moment in the add-on I'll plan to use this case for that purpose. So I'll leave it open for the time being.
